### ISSUE TITLE
V2.0 with USB-C on Aliexpress

### ISSUE THREAD

**Issue by Adammantium** [Szybet/WatchySourcingHub#4]
Just bought from this link and got the watch:
https://de.aliexpress.com/item/1005006764598060
Works perfectly, just the strap is not that good. Maybe you want to add it to the list.

**Comment by Szybet** [comment]
The link doesn't work for me?

It's probably the same supplier, but I will add it anyway once you provide a working link

**Comment by Adammantium** [comment]
Weird, the product is still there.
Does this link work for you?
https://a.aliexpress.com/_mMUPX3M

**Comment by Szybet** [comment]
It works, thanks

Does it say 01Space on the PCB somewhere? Can you take detailed pictures of the PCB like I did with the micro usb version?

**Comment by Adammantium** [comment]
Sure thing
![IMG_20240517_191203](https://github.com/Szybet/WatchySourcingHub/assets/38858318/5d27106c-074a-451c-a1c4-fae9b39a934f)
Edit: I will send some more later

**Comment by Adammantium** [comment]
![IMG_20240517_223309](https://github.com/Szybet/WatchySourcingHub/assets/38858318/7cfab6f0-dc7c-4d9b-b2fa-e8cf99c87ccd)
![IMG_20240517_223343](https://github.com/Szybet/WatchySourcingHub/assets/38858318/36426997-2750-4fb6-926e-2361b3a45072)
![IMG_20240517_223325](https://github.com/Szybet/WatchySourcingHub/assets/38858318/cfb825c4-0542-4a14-8066-e3e2908c5182)

**Comment by Szybet** [comment]
Added them, thanks!
